### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by sducksworth** [motform/arduino-cli-mode#4]
I am currently trying this out on Fedora 31 with Emacs 26.3 and found an issue with the following menu item in arduino-cli-mode.el.

Was:
["Compile Project" arduino-cli-build]

Should be: 
["Compile Project" arduino-cli-compile]

This from version arduino-cli-mode-20200812.935 from elpa.

So far everything else seems to be working fine.

**Comment by motform** [comment]
Hi sducksworth,

Thank you for using the package! Glad to hear it is working out for you. That menu item is definitely referencing the wrong thing, `arduino-cli-build` is an old function that has been superseded with `arduino-cli-compile`, as you point out. 

I have pushed and update that should correct this, hope it solves your issue!
