### ISSUE TITLE
Improve doc

### ISSUE THREAD

**Issue by Ergus** [motform/arduino-cli-mode#5]
Hi:

Just a suggestion. In the use-package snippet you propose in the readme it is simpler to use this:

```
(use-package arduino-cli-mode
  :ensure t
  :mode "\\.ino\\'"
  :custom
  (arduino-cli-warnings 'all)
  (arduino-cli-verify t))
```

BTW: Does this mode conflicts with the arduino-mode? 

https://github.com/stardiviner/arduino-mode

If not, maybe it is better to use a hook instead of the mode to have both.

**Comment by motform** [comment]
That use-package declaration looks a lot more succinct, do you want to submit a pull request to swap it out or should I?

`arduino-cli-mode` is a minor mode and should not conflict with `arduino-mode`, which is a major one. I use both side by side, but there could be some conflict somewhere that I have not encountered. Please report any if you find them!

**Comment by Ergus** [comment]
Hi, feel free to do it yourself.

If the config works with arduino-mode properly, then the config must be:
```
(use-package arduino-cli-mode
  :ensure t
  :hook arduino-mode
  :custom
  (arduino-cli-warnings 'all)
  (arduino-cli-verify t))
```
And let the arduino-mode have the `:mode`

**Comment by motform** [comment]
Cool, that looks great! I really have to dig into use-package some time. I have updated the README and will close this thread. : )
