### ISSUE TITLE
Arduino-mode link in README broken

### ISSUE THREAD

**Issue by togakangaroo** [motform/arduino-cli-mode#7]
Leads to a repo that doesn't exist. Best I can find for the "correct" link is the one [listed here](https://www.emacswiki.org/emacs/ArduinoSupport)

**Comment by motform** [comment]
Oh yeah, you are right, it seems like the author moved it from Github to [repo.or.cz](https://repo.or.cz/arduino-mode.git). It is still available on [Melpa](https://melpa.org/#/arduino-mode), so I'll change the link to that. Thank you for catching!
